server:
  port: 8080

price-collector:
  scheduler:
    cron: "0 */1 * * * *"

spring:
  application:
    name: price-collector-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

core:
  url: http://localhost:8081/api
